name: CI/CD

on: [ push ]

jobs:
  ui-build:
    name: "[UI] Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ui/node_modules
          key: ${{ runner.os }}-targets
      - name: Install dependencies
        working-directory: ui
        run: npm install
      - name: Run Tests
        working-directory: ui
        run: npm test
      - name: Run Linter
        working-directory: ui
        run: npm run lint
      - name: Build
        working-directory: ui
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ui-dist
          path: ui/build
          retention-days: 5

  api-build:
    name: "[API] Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Verify
        working-directory: api
        run: mvn -B clean package
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: api-dist
          path: api/target
          retention-days: 5

  deploy-to-gcp:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    needs:
      - ui-build
      - api-build
    if: success() && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ui-dist
          path: ui/build
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: api-dist
          path: api/target
      - id: auth
        name: Authenticate
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - id: upload-files
        name: Upload UI to cloud storage
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: ui/build
          destination: ${{ secrets.GCP_BUCKET }}
          parent: false
