name: CI

on: [ push ]

jobs:
  Verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-targets
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Run Linter
        run: npm run lint
